export const SET_CURRENT_CHAT = 'SET_CURRENT_CHAT';
export type SET_CURRENT_CHAT = typeof SET_CURRENT_CHAT;

export const ADD_MESSAGES_TO_CHAT = 'ADD_MESSAGES_TO_CHAT';
export type ADD_MESSAGES_TO_CHAT = typeof ADD_MESSAGES_TO_CHAT;

export const ADD_MESSAGE_TO_CHAT = 'ADD_MESSAGE_TO_CHAT';
export type ADD_MESSAGE_TO_CHAT = typeof ADD_MESSAGE_TO_CHAT;

export const CLEAR_MESSAGES_FROM_CHAT = 'CLEAR_MESSAGES_FROM_CHAT';
export type CLEAR_MESSAGES_FROM_CHAT = typeof CLEAR_MESSAGES_FROM_CHAT;

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export type CLEAR_MESSAGES = typeof CLEAR_MESSAGES;

export const CREATE_NEW_MESSAGE = 'CREATE_NEW_MESSAGE';
export type CREATE_NEW_MESSAGE = typeof CREATE_NEW_MESSAGE;

export const CREATE_NEW_MESSAGES = 'CREATE_NEW_MESSAGES';
export type CREATE_NEW_MESSAGES = typeof CREATE_NEW_MESSAGES;

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export type CLEAR_MESSAGE = typeof CLEAR_MESSAGE;

export const GET_CHAT_SERVER_RESPONSE = 'GET_CHAT_SERVER_RESPONSE';
export type GET_CHAT_SERVER_RESPONSE = typeof GET_CHAT_SERVER_RESPONSE;