export const FILTER_LIST_ALPHABETICALLY = 'FILTER_LIST_ALPHABETICALLY';
export type FILTER_LIST_ALPHABETICALLY = typeof FILTER_LIST_ALPHABETICALLY;

export const SET_COIN_DATA = 'SET_COIN_DATA';
export type SET_COIN_DATA = typeof SET_COIN_DATA;

export const SET_AVAILABLE_COIN_LIST = 'SET_AVAILABLE_COIN_LIST';
export type SET_AVAILABLE_COIN_LIST = typeof SET_AVAILABLE_COIN_LIST;

export const SELECT_SORT_BY_MARKET_CAP = 'SELECT_SORT_BY_MARKET_CAP';
export type SELECT_SORT_BY_MARKET_CAP = typeof SELECT_SORT_BY_MARKET_CAP;

export const SELECT_SORT_BY_PRICE = 'SELECT_SORT_BY_PRICE';
export type SELECT_SORT_BY_PRICE = typeof SELECT_SORT_BY_PRICE;

export const SELECT_SORT_BY_NAME = 'SELECT_SORT_BY_NAME';
export type SELECT_SORT_BY_NAME = typeof SELECT_SORT_BY_NAME;

export const CHANGE_MARKET_LIST_CURRENCY = 'CHANGE_MARKET_LIST_CURRENCY';
export type CHANGE_MARKET_LIST_CURRENCY = typeof CHANGE_MARKET_LIST_CURRENCY;

export const SET_HISTORICAL_MARKET_DATA = 'SET_HISTORICAL_MARKET_DATA';
export type SET_HISTORICAL_MARKET_DATA = typeof SET_HISTORICAL_MARKET_DATA;