
export const SELECT_COIN_ICON = 'SELECT_COIN_ICON';
export type SELECT_COIN_ICON = typeof SELECT_COIN_ICON;

export const SELECT_MENU_BAR_LOGIN = 'SELECT_MENU_BAR_LOGIN';
export type SELECT_MENU_BAR_LOGIN = typeof SELECT_MENU_BAR_LOGIN;

export const FILTER_LIST_ALPHABETICALLY = 'FILTER_LIST_ALPHABETICALLY';
export type FILTER_LIST_ALPHABETICALLY = typeof FILTER_LIST_ALPHABETICALLY;